AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with versioning and KMS encryption

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

  KmsKeyId:
    Type: String
    Description: The KMS key ID to use for encryption

  VersioningStatus:
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled
    Description: Versioning status for the S3 bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningStatus
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KmsKeyId

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
