pipeline {
    agent any
    parameters {
  choice choices: ['start', 'reboot', 'stop', 'terminate'], description: 'perform action for ec2', name: 'ACTION'
  string description: 'instance id', name: 'INSTANCE_ID'
}
    environment { 
        SNS_TOPIC_ARN = 'arn:aws:sns:us-east-2:010526277866:pipeline-sns'
    }

    stages {
        stage('perform ec2 action') {
            steps {
                echo "Your ${params.INSTANCE_ID} is now going to ${params.ACTION}"
                sh "aws ec2 ${params.ACTION}-instances --instance-ids ${params.INSTANCE_ID}"
            }
        }
    }
        post { 
        always { 
            sh "aws sns publish --topic-arn ${SNS_TOPIC_ARN} --message "ℹ️ Jenkins Pipeline Completed!\n🎯 EC2 Action: $ACTION\n🔹 Instance ID: $INSTANCE_ID\n📅 Timestamp: $(date)""
        }
        success { 
            sh "aws sns publish --topic-arn ${SNS_TOPIC_ARN} --message "ℹ️ Jenkins Pipeline Successful!\n🎯 EC2 Action: $ACTION\n🔹 Instance ID: $INSTANCE_ID\n📅 Timestamp: $(date)""
        }
        failure { 
            sh "aws sns publish --topic-arn ${SNS_TOPIC_ARN} --message "ℹ️ Jenkins Pipeline Failed!\n🎯 EC2 Action: $ACTION\n🔹 Instance ID: $INSTANCE_ID\n📅 Timestamp: $(date)""
        }
    }
}
