pipeline {
    agent any
    parameters {
  choice choices: ['start', 'reboot', 'stop', 'terminate'], description: 'perform action for ec2', name: 'ACTION'
  string description: 'instance id', name: 'INSTANCE_ID'
}
    environment { 
        SNS_TOPIC_ARN = 'arn:aws:sns:us-east-2:010526277866:pipeline-sns'
    }

    stages {
        stage('Perform EC2 Action') {
            steps {
                echo "Your instance ${params.INSTANCE_ID} is now going to ${params.ACTION}"
                sh "aws ec2 ${params.ACTION}-instances --instance-ids ${params.INSTANCE_ID}"
            }
        }
    }

    post { 
        always { 
            sh """
            aws sns publish --topic-arn ${env.SNS_TOPIC_ARN}  --subject "Jenkins Pipeline Update - Instance ${params.INSTANCE_ID}" --message "jenkins pipeline completed"
            """
        }
        success { 
            sh """
            aws sns publish --topic-arn ${env.SNS_TOPIC_ARN} --message "jenkin pipeline succeeded"
            """
        }
        failure { 
            sh """
            aws sns publish --topic-arn ${env.SNS_TOPIC_ARN} --message "jenkins pipeline failed"
            """
        }
    }
}