pipeline {
    agent any
    triggers {
    // every every sunday at 5pm there will be a cron job
     //   cron('0 17 * * 7') 
        pollSCM('* * * * *')
    }
    environment {
        jenkins_key = credentials('rds-user-password')
        ABC = 'tom'
    }
    stages {
        stage('Print Credentials') {
            steps {
            echo "RDS Password: ${env.jenkins_key}"
            echo "User: ${env.ABC}"
            }
        }
    }
}