pipeline {
    agent any
    triggers {
    // every 1 min there will be a cron job
        cron('*/1 * * * *') 
    }
    environment {
        jenkins_key = credentials('rds-user-password')
        ABC = 'tom'
    }
    stages {
        stage('Print Credentials') {
            steps {
            echo "RDS Password: ${env.jenkins_key}"
            echo "User: ${env.ABC}"
            }
        }
    }
}