pipeline {
    agent any
  
    stages {
        stage('Check existing files') {
            steps {
                script {
                echo "Checking if old files exists"
                sh "ls -l ${WORKSPACE}"
            }
            }
        }
        stage('Generate files') {
            steps {
                
                sh '''
                echo "This is build $(date)" > build_date-$(date +%d%m%y%H%S).txt
                echo "This is temporary data" > tmp-$(date +%d%m%y%H%S).txt
                ls -l 
                '''
            }
        }
    }

    post { 
        cleanup { 
            echo 'we are cleaning up workspace'
            cleanWs()
        }
    }
}